

SELECT DISTINCT

    TO_NUMBER(TO_CHAR(ORDER_DATE,'YYYYMMDD')) AS DATE_KEY,
    CAST(ORDER_DATE AS DATE) AS DATE,
    YEAR(ORDER_DATE) AS YEAR,
    MONTH(ORDER_DATE) AS MONTH,
    DAY(ORDER_DATE) AS DAY

FROM {{ ref('stg_orders_retail') }}