version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_customers_1
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: country
        tests:
          - accepted_values:
              arguments:
                values:
                  - USA
                  - UK
                  - INDIA

  - name: stg_orders_1
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: stg_customers_2
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_customers_2')
                field: customer_id

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

seeds:
  - name: customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null