version: 2

models:
  - name: dim_employee
    columns: 
      - name: emp_id
        tests:
          - unique
          - not_null
      - name: emp_name
        tests:
          - not_null
      - name: dept_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_department')
                field: dept_id
      - name: status
        tests:
          - accepted_values:
              arguments:
                values:
                  - ACTIVE
                  - INACTIVE
          
          