version: 2

sources:
  - name: hr
    database: finance_db
    schema: hr_schema
    tables:
      - name: emp
      - name: dept
  - name: raw
    database: dbt_db
    schema: dbt_schema
    tables:
      - name: raw_customers
      - name: raw_customers_1
      - name: raw_orders
      - name: raw_orders_2