version: 2

sources:
  - name: raw
    database: retail_db
    schema: raw
    tables:
      - name: customers_raw
      - name: products
      - name: orders
      - name: order_items
      - name: returns