SELECT
CUSTOMER_ID,
TRIM(UPPER(CUSTOMER_NAME)) AS CUSTOMER_NAME,
LOWER(EMAIL) AS EMAIL,
PHONE,
 TRIM(CITY) AS CITY,
TRIM(STATE) AS STATE,
COUNTRY,
CREATED_DATE

FROM {{ source('raw','customers_raw') }}

WHERE CUSTOMER_ID IS NOT NULL